/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package cloud.csonic.types.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class OtpEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4133771368927668162L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OtpEvent\",\"namespace\":\"cloud.csonic.types.avro\",\"fields\":[{\"name\":\"Code\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"TransactionId\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"Created\",\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<OtpEvent> ENCODER =
      new BinaryMessageEncoder<OtpEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OtpEvent> DECODER =
      new BinaryMessageDecoder<OtpEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<OtpEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<OtpEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<OtpEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<OtpEvent>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this OtpEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a OtpEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a OtpEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static OtpEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String Code;
  private java.lang.String TransactionId;
  private java.time.Instant Created;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OtpEvent() {}

  /**
   * All-args constructor.
   * @param Code The new value for Code
   * @param TransactionId The new value for TransactionId
   * @param Created The new value for Created
   */
  public OtpEvent(java.lang.String Code, java.lang.String TransactionId, java.time.Instant Created) {
    this.Code = Code;
    this.TransactionId = TransactionId;
    this.Created = Created;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Code;
    case 1: return TransactionId;
    case 2: return Created;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Code = value$ != null ? value$.toString() : null; break;
    case 1: TransactionId = value$ != null ? value$.toString() : null; break;
    case 2: Created = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'Code' field.
   * @return The value of the 'Code' field.
   */
  public java.lang.String getCode() {
    return Code;
  }


  /**
   * Sets the value of the 'Code' field.
   * @param value the value to set.
   */
  public void setCode(java.lang.String value) {
    this.Code = value;
  }

  /**
   * Gets the value of the 'TransactionId' field.
   * @return The value of the 'TransactionId' field.
   */
  public java.lang.String getTransactionId() {
    return TransactionId;
  }


  /**
   * Sets the value of the 'TransactionId' field.
   * @param value the value to set.
   */
  public void setTransactionId(java.lang.String value) {
    this.TransactionId = value;
  }

  /**
   * Gets the value of the 'Created' field.
   * @return The value of the 'Created' field.
   */
  public java.time.Instant getCreated() {
    return Created;
  }


  /**
   * Sets the value of the 'Created' field.
   * @param value the value to set.
   */
  public void setCreated(java.time.Instant value) {
    this.Created = value;
  }

  /**
   * Creates a new OtpEvent RecordBuilder.
   * @return A new OtpEvent RecordBuilder
   */
  public static cloud.csonic.types.avro.OtpEvent.Builder newBuilder() {
    return new cloud.csonic.types.avro.OtpEvent.Builder();
  }

  /**
   * Creates a new OtpEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OtpEvent RecordBuilder
   */
  public static cloud.csonic.types.avro.OtpEvent.Builder newBuilder(cloud.csonic.types.avro.OtpEvent.Builder other) {
    if (other == null) {
      return new cloud.csonic.types.avro.OtpEvent.Builder();
    } else {
      return new cloud.csonic.types.avro.OtpEvent.Builder(other);
    }
  }

  /**
   * Creates a new OtpEvent RecordBuilder by copying an existing OtpEvent instance.
   * @param other The existing instance to copy.
   * @return A new OtpEvent RecordBuilder
   */
  public static cloud.csonic.types.avro.OtpEvent.Builder newBuilder(cloud.csonic.types.avro.OtpEvent other) {
    if (other == null) {
      return new cloud.csonic.types.avro.OtpEvent.Builder();
    } else {
      return new cloud.csonic.types.avro.OtpEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for OtpEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OtpEvent>
    implements org.apache.avro.data.RecordBuilder<OtpEvent> {

    private java.lang.String Code;
    private java.lang.String TransactionId;
    private java.time.Instant Created;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(cloud.csonic.types.avro.OtpEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Code)) {
        this.Code = data().deepCopy(fields()[0].schema(), other.Code);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.TransactionId)) {
        this.TransactionId = data().deepCopy(fields()[1].schema(), other.TransactionId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.Created)) {
        this.Created = data().deepCopy(fields()[2].schema(), other.Created);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing OtpEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(cloud.csonic.types.avro.OtpEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.Code)) {
        this.Code = data().deepCopy(fields()[0].schema(), other.Code);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.TransactionId)) {
        this.TransactionId = data().deepCopy(fields()[1].schema(), other.TransactionId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.Created)) {
        this.Created = data().deepCopy(fields()[2].schema(), other.Created);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'Code' field.
      * @return The value.
      */
    public java.lang.String getCode() {
      return Code;
    }


    /**
      * Sets the value of the 'Code' field.
      * @param value The value of 'Code'.
      * @return This builder.
      */
    public cloud.csonic.types.avro.OtpEvent.Builder setCode(java.lang.String value) {
      validate(fields()[0], value);
      this.Code = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'Code' field has been set.
      * @return True if the 'Code' field has been set, false otherwise.
      */
    public boolean hasCode() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'Code' field.
      * @return This builder.
      */
    public cloud.csonic.types.avro.OtpEvent.Builder clearCode() {
      Code = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'TransactionId' field.
      * @return The value.
      */
    public java.lang.String getTransactionId() {
      return TransactionId;
    }


    /**
      * Sets the value of the 'TransactionId' field.
      * @param value The value of 'TransactionId'.
      * @return This builder.
      */
    public cloud.csonic.types.avro.OtpEvent.Builder setTransactionId(java.lang.String value) {
      validate(fields()[1], value);
      this.TransactionId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'TransactionId' field has been set.
      * @return True if the 'TransactionId' field has been set, false otherwise.
      */
    public boolean hasTransactionId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'TransactionId' field.
      * @return This builder.
      */
    public cloud.csonic.types.avro.OtpEvent.Builder clearTransactionId() {
      TransactionId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'Created' field.
      * @return The value.
      */
    public java.time.Instant getCreated() {
      return Created;
    }


    /**
      * Sets the value of the 'Created' field.
      * @param value The value of 'Created'.
      * @return This builder.
      */
    public cloud.csonic.types.avro.OtpEvent.Builder setCreated(java.time.Instant value) {
      validate(fields()[2], value);
      this.Created = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'Created' field has been set.
      * @return True if the 'Created' field has been set, false otherwise.
      */
    public boolean hasCreated() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'Created' field.
      * @return This builder.
      */
    public cloud.csonic.types.avro.OtpEvent.Builder clearCreated() {
      Created = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OtpEvent build() {
      try {
        OtpEvent record = new OtpEvent();
        record.Code = fieldSetFlags()[0] ? this.Code : (java.lang.String) defaultValue(fields()[0]);
        record.TransactionId = fieldSetFlags()[1] ? this.TransactionId : (java.lang.String) defaultValue(fields()[1]);
        record.Created = fieldSetFlags()[2] ? this.Created : (java.time.Instant) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OtpEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<OtpEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OtpEvent>
    READER$ = (org.apache.avro.io.DatumReader<OtpEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










